spring:  
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/runma
    driverClassName: org.h2.Driver
    username: sa
    password: password    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      